server:
  port: 8867
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.15.79:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&&serverTimezone=GMT
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.15.79
    port: 5672
    username: guest
    password: guest
env:
  test31
girl:
  name: lilia
  age: 19
