server:
  port: 8867
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.15.78:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&&serverTimezone=GMT
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  test
